### ISSUE TITLE
Can't find service on Artix OpenRC

### ISSUE THREAD

**Issue by Dathide** [ilyazzz/LACT#30]
After installing the AUR package with yay, performing
`sudo rc-update add lactd default`
results in
`rc-update: service lactd does not exist`

On the list of all services via `rc-status -s`, there is no lactd.

**Comment by ilyazzz** [comment]
There is no OpenRC entry provided, only a systemd service. All you need for a service is to run `lact-daemon` as root.

**Comment by Dathide** [comment]
Thank you, got it working.
