### ISSUE TITLE
Using junction vs edge temp for fans on newer cards

### ISSUE THREAD

**Issue by Big-FG** [ilyazzz/LACT#43]
Sorry for the 3 different issues at once lol

On newer cards like the 5700xt (and i think vega/radeon vii too?) the junction temp is much more important than the edge temp and determines when throttling occurs. AFAIK this is the temp used on default in the bios fan curves for these cards to determine fan speeds. Might it be possible to use junction temp for creating fan curves vs edge based on card detected? While this isnt absolutely necessary as you can kinda figure what the fan curve should be by monitoring the edge vs junction temp and adjusting accordingly to my knowledge this is the stock behavior but i may just be dense.

Feel free to close this if not interested in it as its not a critical thing

**Comment by ilyazzz** [comment]
Can you post the output of
`cat /sys/class/drm/card0/device/hwmon/*/temp*_label`

Otherwise this should be a fairly trivial fix

**Comment by Big-FG** [comment]
The junction temp for my card is /sys/class/drm/card0/device/hwmon/hwmon0/temp2_label

**Comment by Big-FG** [comment]
just to make sure here is the output

`cat /sys/class/drm/card0/device/hwmon/*/temp*_label
edge
junction
mem
`

**Comment by Big-FG** [comment]
Also just to confirm it was the Radeon VII that junction temp became important

**Comment by Big-FG** [comment]
Also In case it is asked by someone if you decide to add this as to why

The purpose in using junction vs edge on 5700xt and newer cards is that boosting behavior is determined by junction which is w.e the hottest point on the die is. Max junction before hard throttling is 105-110c and shutoff is somewhere around 112-120C depending on the Vbios.

You may end up with an edge temp that "seems" ok but with a junction temp 20-30c higher causing throttling or thermal shutdown. My card for instance usually has a 15-20c delta between edge and junction and as junction increases you lose frequency little by little till hard throttle with mine 107c hard throttle and thermal shutdown at 112c. The lower you keep the junction the better the performance.

**Comment by ilyazzz** [comment]
This is fixed in master now.

**Comment by Big-FG** [comment]
@ilyazzz just wanted to report that its working perfectly and allows much finer control over junction temp. Thanks a lot for adding this, fan now responds long before the junction reaches the 80-90c range and keeping under 90c junction is much easier now.
