### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', gui/src/app/header.rs:55:56

### ISSUE THREAD

**Issue by Big-FG** [ilyazzz/LACT#44]
I had uninstalled LACT doing some testing with some other tools, now when i install the regular LACT from AUR i get this

```
RUST_BACKTRACE=full lact-gui 
Connection to daemon established
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', gui/src/app/header.rs:55:56
stack backtrace:
   0:     0x55dcbe7b2950 - <unknown>
   1:     0x55dcbe7d3d7c - <unknown>
   2:     0x55dcbe7ad725 - <unknown>
   3:     0x55dcbe7b4aab - <unknown>
   4:     0x55dcbe7b4581 - <unknown>
   5:     0x55dcbe7b5184 - <unknown>
   6:     0x55dcbe7b4c27 - <unknown>
   7:     0x55dcbe7b2e4c - <unknown>
   8:     0x55dcbe7b4bb9 - <unknown>
   9:     0x55dcbe3a5651 - <unknown>
  10:     0x55dcbe3a559d - <unknown>
  11:     0x55dcbe3b6749 - <unknown>
  12:     0x7f56eb667030 - g_signal_emit_valist
  13:     0x7f56eb6671a0 - g_signal_emit
  14:     0x7f56eaf7e919 - <unknown>
  15:     0x7f56eaf7eb02 - gtk_combo_box_set_active
  16:     0x55dcbe3b3489 - <unknown>
  17:     0x55dcbe3a8a13 - <unknown>
  18:     0x55dcbe3aebff - <unknown>
  19:     0x55dcbe3ba1a3 - <unknown>
  20:     0x55dcbe3ad439 - <unknown>
  21:     0x55dcbe7b578a - <unknown>
  22:     0x55dcbe3aedc2 - <unknown>
  23:     0x7f56ea593b25 - __libc_start_main
  24:     0x55dcbe3a5e2e - <unknown>
  25:                0x0 - <unknown>
```

LACT-git still works and is building an older version from april but if I update the pkgbuild for the latest git it also crashes with this.

**Comment by Big-FG** [comment]
Discovered what is causing it

The junction temp change that i had suggested previously is causing the gui to crash for some reason.

https://github.com/ilyazzz/LACT/commit/a7d203c7d553dae7dea31ad13cad650367c4559b

**Comment by Big-FG** [comment]
I threw together a quick patch just to test it as i had started at reverting the GTK migration and bump deps from the same day.

Just making sure im reverting ONLY the junction patch

[test.txt](https://github.com/ilyazzz/LACT/files/7171609/test.txt)

**Comment by Big-FG** [comment]
I managed to fix this for myself by changing the systemd unit
```

[Unit]
Description=AMDGPU Control Daemon
After=graphical.target

[Service]
ExecStart=/usr/bin/lact-daemon

[Install]
WantedBy=display-manager.service
```

This seems to work consistently across reboots, why all the sudden it wasnt working anymore I dont know as Im not familiar enough with systemd stuff. Im not sure this is a good solution though but it has it workin in the mean time

**Comment by ilyazzz** [comment]
Sometimes there seems to be an issue where the systemd unit starts too early in the boot process, before the SysFS is properly initialized. I hoped specifying `After=multi-user.target` would fix it, but I guess not. I'm not sure about
```
[Install]
WantedBy=display-manager.service
```
though, since the service doesn't have much to do with the display manager, but I guess it does have to be `WantedBy` by something.

**Comment by Big-FG** [comment]
Yeah Im not so sure about 

```
[Install]
WantedBy=display-manager.service
```
I was trying to think of something around graphical target but before login and it seemed like an OK choice but as for it being a real solution I dont think so. Im not positive a systemd unit needs a wanted by though as some of them dont have it but I only mildly get how systemd units work so i cant say for certain.

**Comment by ilyazzz** [comment]
I would also prefer to avoid depending on `grapahical.target` or `display-manager.service` as that wouldn't work properly on headless systems. Considering that the bug seems to be some kind of race condition from my experience, a crappy but probably functional workaround would be to just add a couple of seconds of waiting before the unit starts.

**Comment by Big-FG** [comment]
Ill give that a try and see if that works out, thatd probably be much better than doing something that doesnt work for headless.

**Comment by Big-FG** [comment]
Yeah after multiple reboots this seems to solve the issue, before that even just one reboot would force me to have to restart the daemon but after 5 reboots no issues.

`ExecStartPre=/bin/sleep 2`

I didnt even think of that even though i already do that with GDM x3 was making it more complicated than i needed to changing wantedby and such.

**Comment by ilyazzz** [comment]
@Big-FG I've updated the `lact-git` package in the AUR to include this, hopefully it fixes the issue.
